;******************Juego de triki********************
;*****Presentado por: Carlos Daniel Londoño Avila****
;******************Programación I********************
;---------------------------------------------------------------------------------------------

;llamamos a la libreria.
(require (lib"graphics"))
(open-graphics)

;Creamos una ventana.
(define Miventana (open-viewport "TRIKI" 512 512))

;Insertamos la imagen de inicio en la ventana.
(define (inicio)
((draw-pixmap Miventana) "inicio.png" (make-posn 0.0 0.0))
(sleep 2) ;esperamos 2 segundos para que aparezca el menú en pantalla.
((clear-viewport Miventana))
((draw-pixmap Miventana) "menú.png" (make-posn 0.0 0.0)))

;----------------AQUI LEEMOS LA POSICION DONDE SE DIO CLICK EN LA VENTANA DEL MENÚ--------------

(define (click-menu click)
  (click-Miventana-menu (get-mouse-click Miventana))
  )
(define (click-Miventana-menu ventana)
  (posicion-click-menu (mouse-click-posn ventana))
  )
(define (posicion-click-menu posicion)
  (cambiar-ventana-menu (posn-x posicion) (posn-y posicion))
  )
(define (cambiar-ventana-menu posn-x posn-y)
  (if (and (>= posn-x 176) (<= posn-x 321)
           (>= posn-y 68) (<= posn-y 134)
           )
        (begin
          ((clear-viewport Miventana))
          ((draw-pixmap Miventana) "tablero.png" (make-posn 0.0 0.0))
          (click-tablero 0 1 0 0 0 0 0 0 0 0 0)
          )
         (if (and (>= posn-x 178) (<= posn-x 320)
                  (>= posn-y 175) (<= posn-y 238)
                )
              (begin
                ((clear-viewport Miventana))
                ((draw-pixmap Miventana) "ayuda.png" (make-posn 0.0 0.0))
                (click-ayuda 0)
               )
               (if (and (>= posn-x 178) (<= posn-x 318)
                        (>= posn-y 282) (<= posn-y 344)
                     )
                   (begin
                     ((clear-viewport Miventana))
                     ((draw-pixmap Miventana) "creditos.png" (make-posn 0.0 0.0))
                     (click-creditos 0)
                     )
                   (if (and (>= posn-x 180) (<= posn-x 321)
                            (>= posn-y 386) (<= posn-y 448)
                         )
                        (close-viewport Miventana)
                        (click-menu 0)
                        )
                   )
               )
         )
  )
;---------------AQUI LEEMOS EL CLICK EN LA VENTANA AYUDA, PARA RETORNAR AL MENÚ.----------------

(define (click-ayuda click)
  (click-Miventana-ayuda (get-mouse-click Miventana))
  )
(define (click-Miventana-ayuda ventana)
  (posicion-click-ayuda (mouse-click-posn ventana))
  )
(define (posicion-click-ayuda posicion)
  (cambiar-ventana-ayuda (posn-x posicion) (posn-y posicion))
  )
(define (cambiar-ventana-ayuda posn-x posn-y)
  (if (and (>= posn-x 183) (<= posn-x 309)
           (>= posn-y 444) (<= posn-y 506)
           )
        (begin
          ((clear-viewport Miventana))
          ((draw-pixmap Miventana) "menú.png" (make-posn 0.0 0.0))
          (click-menu 0)
         )
        (click-ayuda 0)
      )
  )
;---------------AQUI LEEMOS EL CLICK EN LA VENTANA CREDITOS, PARA RETORNAR AL MENÚ----------------

(define (click-creditos click)
  (click-Miventana-creditos (get-mouse-click Miventana))
  )
(define (click-Miventana-creditos ventana)
  (posicion-click-creditos (mouse-click-posn ventana))
  )
(define (posicion-click-creditos posicion)
  (cambiar-ventana-creditos (posn-x posicion) (posn-y posicion))
  )
(define (cambiar-ventana-creditos posn-x posn-y)
  (if (and (>= posn-x 174) (<= posn-x 306)
           (>= posn-y 425) (<= posn-y 491)
           )
        (begin
          ((clear-viewport Miventana))
          ((draw-pixmap Miventana) "menú.png" (make-posn 0.0 0.0))
          (click-menu 0)
          )
        (click-creditos 0)
        )
  )
;-----------AQUI DEFINIMOS LAS 3 FILAS Y LAS 3 COLUMNAS DEL TABLERO------------

(define fila1 (make-vector 3 "?" ))
(define fila2 (make-vector 3 "?" ))
(define fila3 (make-vector 3 "?" ))

(define columna1 (make-vector 3 "?" ))
(define columna2 (make-vector 3 "?" ))
(define columna3 (make-vector 3 "?" ))

;---------------AQUI LEEMOS EL CLICK EN EL TABLERO DEL TRIKI-------------------

(define (click-tablero click cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
  (click-Miventana-tablero (get-mouse-click Miventana) cont c1 c2 c3 c4 c5 c6 c7 c8 c9) ;los parametros c1 c2 c3 c4 c5 c6 c7 c8 c9 son el numero de clicks en
  )                                                                                     ;cada uno de los 9 cuadros de tablero y se crearon para que solo se pueda
(define (click-Miventana-tablero ventana cont c1 c2 c3 c4 c5 c6 c7 c8 c9)               ;leer un solo click por cuadro y no se agregue una X encima de una O
  (posicion-click-tablero (mouse-click-posn ventana) cont c1 c2 c3 c4 c5 c6 c7 c8 c9)   ;y viceversa.
  )
(define (posicion-click-tablero posicion cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
  (final posicion cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
  )
(define (final posicion cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
      (jugar (posn-x posicion) (posn-y posicion) cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
 )
;----------------AQUI INSERTAMOS LA "X" Ó LA "O" EN EL MINICUADRO QUE NOS INDIQUEN LOS DOS JUGADORES------------------

(define (jugar x y cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
        (if (and (>= x 14) (<= x 163) (>= y 17) (<= y 161))
           (if (= c1 0)
            (if (= (remainder cont 2) 0)
                (begin
                  ((draw-pixmap Miventana) "O.png" (make-posn 20 20))
                  ;Escribir en la F1C1 una "O"
                  (vector-set! fila1 0 "O")
                  (vector-set! columna1 0 "O")
                  (linea-triki (+ cont 1) (+ c1 1) c2 c3 c4 c5 c6 c7 c8 c9)
                 )
                (begin
                  ((draw-pixmap Miventana) "X.png" (make-posn 20 20))
                  ;Escribir en la F1C1 una "X"
                  (vector-set! fila1 0 "X")
                  (vector-set! columna1 0 "X")
                  (linea-triki (+ cont 1) (+ c1 1) c2 c3 c4 c5 c6 c7 c8 c9)
                 )
              )
            (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9) 
            )
             (if (and (>= x 13) (<= x 163) (>= y 173) (<= y 333))
                 (if (= c2 0)
                   (if (= (remainder cont 2) 0)
                     (begin
                       ((draw-pixmap Miventana) "O.png" (make-posn 20 183))
                       ;Escribir en la F2C1 una "O"
                       (vector-set! fila2 0 "O")
                       (vector-set! columna1 1 "O")
                       (linea-triki (+ cont 1) c1 (+ c2 1) c3 c4 c5 c6 c7 c8 c9)
                      )
                      (begin
                       ((draw-pixmap Miventana) "X.png" (make-posn 20 183))
                       ;Escribir en la F2C1 una "X"
                       (vector-set! fila2 0 "X")
                       (vector-set! columna1 1 "X")
                       (linea-triki (+ cont 1) c1 (+ c2 1) c3 c4 c5 c6 c7 c8 c9)
                      )
                   )
                   (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                 )
                  (if (and (>= x 13) (<= x 164) (>= y 342) (<= y 499))
                     (if (= c3 0)
                      (if (= (remainder cont 2) 0)
                          (begin
                            ((draw-pixmap Miventana) "O.png" (make-posn 20 349))
                            ;Escribir en la F3C1 una "O"
                            (vector-set! fila3 0 "O")
                            (vector-set! columna1 2 "O")
                            (linea-triki (+ cont 1) c1 c2 (+ c3 1) c4 c5 c6 c7 c8 c9)
                           )
                           (begin
                             ((draw-pixmap Miventana) "X.png" (make-posn 20 349))
                             ;Escribir en la F3C1 una "X"
                             (vector-set! fila3 0 "X")
                             (vector-set! columna1 2 "X")
                             (linea-triki (+ cont 1) c1 c2 (+ c3 1) c4 c5 c6 c7 c8 c9)
                            )
                        )
                      (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                      )
                       (if (and (>= x 173) (<= x 333) (>= y 16) (<= y 163))
                          (if (= c4 0)
                           (if (= (remainder cont 2) 0)
                               (begin
                                 ((draw-pixmap Miventana) "O.png" (make-posn 180 20))
                                 ;Escribir en la F1C2 una "O"
                                 (vector-set! fila1 1 "O")
                                 (vector-set! columna2 0 "O")
                                 (linea-triki (+ cont 1) c1 c2 c3 (+ c4 1) c5 c6 c7 c8 c9)
                                )
                               (begin
                                 ((draw-pixmap Miventana) "X.png" (make-posn 180 20))
                                 ;Escribir en la F1C2 una "X"
                                 (vector-set! fila1 1 "X")
                                 (vector-set! columna2 0 "X")
                                 (linea-triki (+ cont 1) c1 c2 c3 (+ c4 1) c5 c6 c7 c8 c9)
                                )
                             )
                           (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                           )
                            (if (and (>= x 173) (<= x 333) (>= y 173) (<= y 333))
                              (if (= c5 0)
                                (if (= (remainder cont 2) 0)
                                    (begin
                                      ((draw-pixmap Miventana) "O.png" (make-posn 180 183))
                                      ;Escribir en la F2C2 una "O"
                                      (vector-set! fila2 1 "O")
                                      (vector-set! columna2 1 "O")
                                      (linea-triki (+ cont 1) c1 c2 c3 c4 (+ c5 1) c6 c7 c8 c9) 
                                     ) 
                                    (begin
                                      ((draw-pixmap Miventana) "X.png" (make-posn 180 183))
                                      ;Escribir en la F2C2 una "X"
                                      (vector-set! fila2 1 "X")
                                      (vector-set! columna2 1 "X")
                                      (linea-triki (+ cont 1) c1 c2 c3 c4 (+ c5 1) c6 c7 c8 c9)
                                     )
                                 )
                                (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                               )
                                (if (and (>= x 173) (<= x 333) (>= y 343) (<= y 499))
                                   (if (= c6 0)
                                    (if (= (remainder cont 2) 0)
                                        (begin
                                          ((draw-pixmap Miventana) "O.png" (make-posn 180 350))
                                          ;Escribir en la F3C2 una "O"
                                          (vector-set! fila3 1 "O")
                                          (vector-set! columna2 2 "O")
                                          (linea-triki (+ cont 1) c1 c2 c3 c4 c5 (+ c6 1) c7 c8 c9)
                                         )
                                        (begin
                                          ((draw-pixmap Miventana) "X.png" (make-posn 180 350))
                                          ;Escribir en la F3C2 una "X"
                                          (vector-set! fila3 1 "X")
                                          (vector-set! columna2 2 "X")
                                          (linea-triki (+ cont 1) c1 c2 c3 c4 c5 (+ c6 1) c7 c8 c9)
                                         )
                                      )
                                    (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                                    )
                                    (if (and (>= x 342) (<= x 499) (>= y 16) (<= y 163))
                                        (if (= c7 0)
                                         (if (= (remainder cont 2) 0)
                                             (begin
                                               ((draw-pixmap Miventana) "O.png" (make-posn 353 20))
                                               ;Escribir en la F1C3 una "O"
                                               (vector-set! fila1 2 "O")
                                               (vector-set! columna3 0 "O")
                                               (linea-triki (+ cont 1) c1 c2 c3 c4 c5 c6 (+ c7 1) c8 c9)
                                              )
                                             (begin
                                                ((draw-pixmap Miventana) "X.png" (make-posn 353 20))
                                                ;Escribir en la F1C3 una "X"
                                                (vector-set! fila1 2 "X")
                                                (vector-set! columna3 0 "X")
                                                (linea-triki (+ cont 1) c1 c2 c3 c4 c5 c6 (+ c7 1) c8 c9)
                                              )
                                           )
                                         (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                                         )
                                         (if (and (>= x 342) (<= x 499) (>= y 172) (<= y 333))
                                            (if (= c8 0)
                                             (if (= (remainder cont 2) 0)
                                                 (begin
                                                   ((draw-pixmap Miventana) "O.png" (make-posn 353 183))
                                                   ;Escribir en la F2C3 una "O"
                                                   (vector-set! fila2 2 "O")
                                                   (vector-set! columna3 1 "O")
                                                   (linea-triki (+ cont 1) c1 c2 c3 c4 c5 c6 c7 (+ c8 1) c9)
                                                  )
                                                 (begin
                                                   ((draw-pixmap Miventana) "X.png" (make-posn 353 183))
                                                   ;Escribir en la F2C3 una "X"
                                                   (vector-set! fila2 2 "X")
                                                   (vector-set! columna3 1 "X")
                                                   (linea-triki (+ cont 1) c1 c2 c3 c4 c5 c6 c7 (+ c8 1) c9)
                                                  )
                                               )
                                             (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                                             )
                                            (if (and (>= x 342) (<= x 499) (>= y 344) (<= y 499))
                                                (if (= c9 0)
                                                 (if (= (remainder cont 2) 0)
                                                     (begin
                                                       ((draw-pixmap Miventana) "O.png" (make-posn 353 350))
                                                       ;Escribir en la F3C3 una "O"
                                                       (vector-set! fila3 2 "O")
                                                       (vector-set! columna3 2 "O")
                                                       (linea-triki (+ cont 1) c1 c2 c3 c4 c5 c6 c7 c8 (+ c9 1))
                                                      )
                                                      (begin
                                                        ((draw-pixmap Miventana) "X.png" (make-posn 353 350))
                                                        ;Escribir en la F3C3 una "X"
                                                        (vector-set! fila3 2 "X")
                                                        (vector-set! columna3 2 "X")
                                                        (linea-triki (+ cont 1) c1 c2 c3 c4 c5 c6 c7 c8 (+ c9 1))
                                                       )
                                                   )
                                                 (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                                                 )
                                                 (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                                                )
                                         )
                                     )
                                )
                            )
                       )
                   )
             )
        )
  )
         
;-----------AQUI INSERTAMOS EN EL TABLERO LA LINEA QUE RESALTA E INDICA QUE UN JUGADOR HIZO "TRIKI"---------------

(define (linea-triki cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
  (if (equal? fila1 #("X" "X" "X"))
      (begin
           ((draw-pixmap Miventana)"linea.png" (make-posn 13 87)) 
           (sleep 1)
           ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
           ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
           ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
           ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
           (click-jugar-de-nuevo 0)
           )
         (if (equal? fila1 #("O" "O" "O"))
          (begin
           ((draw-pixmap Miventana)"E:/Pictures/imagenesracket/linea.png" (make-posn 13 87)) 
           (sleep 1)
           ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
           ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
           ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
           ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
           (click-jugar-de-nuevo 0)
           )
          (if (equal? fila2 #("X" "X" "X"))
              (begin
                ((draw-pixmap Miventana)"linea.png" (make-posn 14 251)) 
                (sleep 1)
                ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
                ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                (click-jugar-de-nuevo 0)
               )
              (if (equal? fila2 #("O" "O" "O"))
               (begin
                ((draw-pixmap Miventana)"linea.png" (make-posn 14 251)) 
                (sleep 1)
                ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
                ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                (click-jugar-de-nuevo 0)
               )
              (if (equal? fila3 #("X" "X" "X"))
                  (begin
                    ((draw-pixmap Miventana)"linea.png" (make-posn 14 416)) 
                    (sleep 1)
                    ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
                    ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                    ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                    ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                    (click-jugar-de-nuevo 0)
                    )
                   (if (equal? fila3 #("O" "O" "O"))
                      (begin
                        ((draw-pixmap Miventana)"linea.png" (make-posn 14 416)) 
                        (sleep 1)
                        ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
                        ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                        ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                        ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                        (click-jugar-de-nuevo 0)
                      )
                   (if (equal? columna1 #("X" "X" "X"))
                       (begin
                         ((draw-pixmap Miventana)"linea2.png" (make-posn 86 14)) 
                         (sleep 1)
                         ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
                         ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                         ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                         ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                         (click-jugar-de-nuevo 0)
                        )
                       (if (equal? columna1 #("O" "O" "O"))
                        (begin
                         ((draw-pixmap Miventana)"linea2.png" (make-posn 86 14)) 
                         (sleep 1)
                         ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
                         ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                         ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                         ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                         (click-jugar-de-nuevo 0)
                        )
                       (if (equal? columna2 #("X" "X" "X"))
                           (begin
                             ((draw-pixmap Miventana)"linea2.png" (make-posn 246 14)) 
                             (sleep 1)
                             ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
                             ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                             ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                             ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                             (click-jugar-de-nuevo 0)
                             )
                           (if (equal? columna2 #("O" "O" "O"))
                            (begin
                             ((draw-pixmap Miventana)"linea2.png" (make-posn 246 14)) 
                             (sleep 1)
                             ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
                             ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                             ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                             ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                             (click-jugar-de-nuevo 0)
                             )
                            (if (equal? columna3 #("X" "X" "X"))
                                (begin
                                  ((draw-pixmap Miventana) "linea2.png" (make-posn 420 14)) 
                                  (sleep 1)
                                  ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
                                  ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                                  ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                                  ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                                  (click-jugar-de-nuevo 0)
                                  )
                               (if (equal? columna3 #("O" "O" "O"))
                                   (begin
                                    ((draw-pixmap Miventana)"linea2.png" (make-posn 420 14)) 
                                    (sleep 1)
                                    ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
                                    ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                                    ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                                    ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                                    (click-jugar-de-nuevo 0)
                                  )
                                (if (and (equal? (vector-ref fila1 0) "X")
                                         (equal? (vector-ref fila2 1) "X")
                                         (equal? (vector-ref fila3 2) "X")
                                       )
                                    (begin
                                      ((draw-line Miventana) (make-posn 11 13) (make-posn 497 499) "yellow")
                                      ((draw-line Miventana) (make-posn 12 13) (make-posn 498 499) "yellow")
                                      ((draw-line Miventana) (make-posn 13 13) (make-posn 499 499) "yellow")
                                      ((draw-line Miventana) (make-posn 14 13) (make-posn 500 499) "yellow")
                                      ((draw-line Miventana) (make-posn 15 13) (make-posn 501 499) "yellow")
                                      (sleep 1)
                                      ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
                                      ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                                      ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                                      ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                                      (click-jugar-de-nuevo 0)
                                      )
                                    (if (and (equal? (vector-ref fila1 0) "O")
                                             (equal? (vector-ref fila2 1) "O")
                                             (equal? (vector-ref fila3 2) "O")
                                           )
                                          (begin
                                            ((draw-line Miventana) (make-posn 11 13) (make-posn 497 499) "yellow")
                                            ((draw-line Miventana) (make-posn 12 13) (make-posn 498 499) "yellow")
                                            ((draw-line Miventana) (make-posn 13 13) (make-posn 499 499) "yellow")
                                            ((draw-line Miventana) (make-posn 14 13) (make-posn 500 499) "yellow")
                                            ((draw-line Miventana) (make-posn 15 13) (make-posn 501 499) "yellow")
                                            (sleep 1)
                                            ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
                                            ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                                            ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                                            ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                                            (click-jugar-de-nuevo 0)
                                           )
                                          (if (and (equal? (vector-ref fila1 2) "X")
                                                   (equal? (vector-ref fila2 1) "X")
                                                   (equal? (vector-ref fila3 0) "X") 
                                                 )
                                               (begin
                                               ((draw-line Miventana) (make-posn 497 13) (make-posn 13 497) "yellow")
                                               ((draw-line Miventana) (make-posn 498 13) (make-posn 13 498) "yellow")
                                               ((draw-line Miventana) (make-posn 499 13) (make-posn 13 499) "yellow")
                                               ((draw-line Miventana) (make-posn 500 13) (make-posn 13 500) "yellow")
                                               ((draw-line Miventana) (make-posn 501 13) (make-posn 13 501) "yellow")
                                               (sleep 1)
                                               ((draw-pixmap Miventana) "jugador1.png" (make-posn 161 155))
                                               ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                                               ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                                               ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                                               (click-jugar-de-nuevo 0)
                                                )
                                               (if (and (equal? (vector-ref fila1 2) "O")
                                                        (equal? (vector-ref fila2 1) "O")
                                                        (equal? (vector-ref fila3 0) "O")
                                                     )
                                                     (begin
                                                        ((draw-line Miventana) (make-posn 497 13) (make-posn 13 497) "yellow")
                                                        ((draw-line Miventana) (make-posn 498 13) (make-posn 13 498) "yellow")
                                                        ((draw-line Miventana) (make-posn 499 13) (make-posn 13 499) "yellow")
                                                        ((draw-line Miventana) (make-posn 500 13) (make-posn 13 500) "yellow")
                                                        ((draw-line Miventana) (make-posn 501 13) (make-posn 13 501) "yellow")
                                                        (sleep 1)
                                                        ((draw-pixmap Miventana) "jugador2.png" (make-posn 161 155))
                                                        ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                                                        ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                                                        ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                                                        (click-jugar-de-nuevo 0)
                                                      )
                                                     (if (= cont 10)
                                                        (begin
                                                         (sleep 0.5)
                                                         ((draw-pixmap Miventana) "empate.png" (make-posn 161 155))
                                                         ((draw-pixmap Miventana) "jugardenuevo.png" (make-posn 173 185))
                                                         ((draw-pixmap Miventana) "volveralmenú.png" (make-posn 173 240))
                                                         ((draw-pixmap Miventana) "salirdeljuego.png" (make-posn 173 295))
                                                         (click-jugar-de-nuevo 0)
                                                        )
                                                       (click-tablero 0 cont c1 c2 c3 c4 c5 c6 c7 c8 c9)
                                                      )
                                                   )
                                               )
                                            )
                                        )
                                    )
                                 )
                              )
                           )
                        )
                     )
                  )
               )
            )
          )
       )
    )
 )                 
;------------AQUI LEEMOS EL CLICK DESPUES DE QUE UN JUGADOR GANE EL JUEGO------------------

(define (click-jugar-de-nuevo click)
  (click-ventana-jugar-de-nuevo (get-mouse-click Miventana))
  )
(define (click-ventana-jugar-de-nuevo ventana)
  (posicion-click-jugar-de-nuevo (mouse-click-posn ventana))
  )
(define (posicion-click-jugar-de-nuevo posicion)
  (jugar-de-nuevo (posn-x posicion) (posn-y posicion))
  )
(define (jugar-de-nuevo posn-x posn-y)
        (if (and (>= posn-x 173) (<= posn-x 333)
                 (>= posn-y 185) (<= posn-y 215)
              )
            (begin
              ((clear-viewport Miventana))
              (vector-fill! fila1 "?")
              (vector-fill! fila2 "?")
              (vector-fill! fila3 "?")
              (vector-fill! columna1 "?")
              (vector-fill! columna2 "?")
              (vector-fill! columna3 "?")
              ((draw-pixmap Miventana) "tablero.png" (make-posn 0.0 0.0))
              (click-tablero 0 1 0 0 0 0 0 0 0 0 0)
              )
            (if (and (>= posn-x 173) (<= posn-x 333)
                     (>= posn-y 240) (<= posn-y 270)
                  )
                (begin
                 ((clear-viewport Miventana))
                 (vector-fill! fila1 "?")
                 (vector-fill! fila2 "?")
                 (vector-fill! fila3 "?")
                 (vector-fill! columna1 "?")
                 (vector-fill! columna2 "?")
                 (vector-fill! columna3 "?")
                 ((draw-pixmap Miventana) "menú.png" (make-posn 0.0 0.0))
                 (click-menu 0)
                 )
                (if (and (>= posn-x 173) (<= posn-x 333)
                         (>= posn-y 295) (<= posn-y 325)
                      )
                      (close-viewport Miventana)
                      (click-jugar-de-nuevo 0)
                   )
              )
        )
  )
;----------------------------------------------------------------------------------------------------------------------------------------                        
;llamado
(inicio)
(click-menu 0)


